import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Sidebar configuration
 * Работает с автогенерацией и TypeDoc
 */
const sidebars: SidebarsConfig = {
  /**
   * Основная документация проекта
   * docs/
   */
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],

  /**
   * API документация
   * docs/api (TypeDoc markdown)
   */
  apiSidebar: [
    {
      type: "autogenerated",
      dirName: "api",
    },
  ],
};

export default sidebars;
