import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here.

/**
 * Sidebars configuration
 */
const sidebars: SidebarsConfig = {
  // Автогенерация обычной документации
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // Автогенерация API из каталога docs/api
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
