import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Явный sidebar — production-вариант
 * ❌ без autogenerated
 * ✅ полный контроль маршрутов
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    "getting-started",
    "project-architecture",
    "folder-structure",
    "ci-cd",
    "testing",
    "scripts",
  ],
};

export default sidebars;
